<?php
$arr=[
    '4shared'=>'https://www.4shared.com/web/q/#query=%s&sort=size%2Cdesc',
    'acronimos'=>'https://www.acronymfinder.com/~/search/af.aspx?string=exact&Acronym=%s',
    'alexa'=>'https://alexa.com/siteinfo/%s',
    'amazon brasil'=>'https://www.amazon.com.br/s?k=%s&s=price-asc-rank&dc&ref=sr_st_price-asc-rank',
    'antônimos'=>'https://www.antonimos.com.br/busca.php?q=%s',
    'artigos científicos (researchgate)'=>'https://www.researchgate.net/search?q=%s',
    'atom'=>'https://atom.io/packages/search?q=%s',
    'books'=>'https://b-ok.lat/s/?q=%s',
    'buscape'=>'https://www.buscape.com.br/search?page=1&invalidPath=false&sortBy=prod_items_sort_by_price_asc&q=%s&no-shortcut=1',
    'cdnjs'=>'https://cdnjs.com/libraries?q=%s',
    'dailymotion'=>'https://www.dailymotion.com/search/%s/videos',
    'discogs'=>'https://www.discogs.com/search/?q=%s&type=all',
    'docs em espanhol'=>'https://www.documaniatv.com/search.php?keywords=%',
    'emojipedia'=>'https://emojipedia.org/search/?q=%s',
    'extensão'=>'https://addons.mozilla.org/en-US/firefox/search/?q=%s&type=extension',
    'farmácia (são joão)'=>'https://www.saojoaofarmacias.com.br/search.html?query=%s&type=lowest',
    'fricke'=>'https://www.loja.fricke.com.br/loja/busca.php?palavra_busca=%s',
    'genius'=>'https://genius.com/search?q=%s',
    'github'=>'https://github.com/search?q=+%s+&type=repositories',
    'globo play'=>'https://globoplay.globo.com/busca/?q=%s',
    'imdb'=>'https://www.imdb.com/find?q=%s&ref_=nv_sr_sm',
    'icone'=>'https://fontawesome.com/icons?d=gallery&p=2&q=%s&s=brands,duotone,light,regular,solid&m=free',
    'infopedia'=>'https://www.infopedia.pt/dicionarios/lingua-portuguesa/%s',
    'last.fm'=>'https://www.last.fm/search?q=%s',
    'letras'=>'https://www.letras.mus.br/?q=%s',
    'maps (google)'=>'https://www.google.com.br/maps?hl=pt&q=%s',
    'mercado livre'=>'https://lista.mercadolivre.com.br/%s/_OrderId_PRICE',  
    'music'=>'https://music.youtube.com/search?q=%s',
    'packagist'=>'https://packagist.org/?query=%s',
    'php'=>'https://www.php.net/manual-lookup.php?pattern=%s&scope=quickref',
    'scihub'=>'https://scihubtw.tw/%s',
    'sinônimos'=>'https://www.sinonimos.com.br/busca.php?q=%s',
    'tld-list'=>'https://tld-list.com/tld/%s',
    'twitter'=>'https://twitter.com/search?q=%s+lang%3Apt%20filter%3Averified&src=typd&f=live&vertical=default',
    'whosampled'=>'https://www.whosampled.com/search/?q=%s',
    'wikipedia'=>'https://pt.wikipedia.org/wiki/Special:Search?search=%s&go=Go&ns0=1'
];
ksort($arr);
return $arr;
